spring:
#  thymeleaf:
#    cache: false
#    suffix: .html
  datasource:

    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/eartao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080
mybatis:
  mapperLocations: classpath:mybatis/*.xml
#  servlet:
#    context-path: /priceCheck


#mybatis:
#  mapper-locations: classpath:com/example/demo/mapper/*.xml
#java -jar demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev
#java -jar demo-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

